/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "nxapi_shop_constants.h"

namespace nxapi_shop {

const nxapi_shopConstants g_nxapi_shop_constants;

nxapi_shopConstants::nxapi_shopConstants() {
}

} // namespace

