/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef nxapi_shop_CONSTANTS_H
#define nxapi_shop_CONSTANTS_H

#include "nxapi_shop_types.h"

namespace nxapi_shop {

class nxapi_shopConstants {
 public:
  nxapi_shopConstants();

};

extern const nxapi_shopConstants g_nxapi_shop_constants;

} // namespace

#endif
